// ============================================================
// PELADA APP - Multi-Tenant + Multi-Admin + Financeiro (app.js)
// ============================================================

const SUPABASE_URL = 'https://ajtguipxovhsnxqxgheb.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdGd1aXB4b3Zoc254cXhnaGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NjUwMjcsImV4cCI6MjA5MTE0MTAyN30.PHCHmSwG2K4I2QzsJ4Jc_1qq_Ya9ryNtvFmFocH9ZCA';
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

var grupoAtual=null,currentUser=null,isAdm=false,isSuperAdmin=false,peladaAtual=null,allPeladas=[],admName='',admPassword='',admNames=[],superAdminName='',cachedJogadores=[],cachedPresentes=[],realtimeChannel=null;
var finConfig=null,finMesSelecionado=null;

function dn(n){if(!n)return'';if(admNames.indexOf(n)>-1)return n.replace(' (ADM)','');return n;}
function sa(a){return a.slice().sort(function(x,y){return x.localeCompare(y);});}
function $(id){return document.getElementById(id);}
function showSkeleton(id){var e=$(id);if(e)e.innerHTML='<div class="skeleton"></div>';}
function showToast(m,err){var e=$('toast');e.textContent=m;e.className='toast'+(err?' error':'');setTimeout(function(){e.classList.add('show');},10);setTimeout(function(){e.classList.remove('show');},3000);}
function logAsync(u,a,d){sb.from('logs').insert({usuario:u,acao:a,detalhes:d||'',grupo_id:grupoAtual.id}).then();}
function fmtMes(ym){var p=ym.split('-');var n=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];return n[parseInt(p[1])-1]+'/'+p[0];}
function mesAtual(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');}
function fmtBRL(v){return'R$ '+Number(v).toFixed(2).replace('.',',');}
function gerarMeses(ini,fim){var ms=[],p=ini.split('-'),y=parseInt(p[0]),m=parseInt(p[1]),fp=fim.split('-'),fy=parseInt(fp[0]),fm=parseInt(fp[1]);while(y<fy||(y===fy&&m<=fm)){ms.push(y+'-'+String(m).padStart(2,'0'));m++;if(m>12){m=1;y++;}}return ms;}
function applyTheme(t){if(t==='light')document.documentElement.classList.add('light');else document.documentElement.classList.remove('light');var i=t==='light'?'☀️':'🌙';document.querySelectorAll('.theme-toggle-btn').forEach(function(b){b.textContent=i;});}
function toggleTheme(){var l=document.documentElement.classList.contains('light');var t=l?'dark':'light';try{localStorage.setItem('pelada-theme',t);}catch(e){}applyTheme(t);}
(function(){try{applyTheme(localStorage.getItem('pelada-theme')||'dark');}catch(e){applyTheme('dark');}})();

// === GRUPO ===
window.addEventListener('load',async function(){$('loadingOverlay').style.display='none';showGrupoScreen();});
async function showGrupoScreen(){grupoAtual=null;currentUser=null;isAdm=false;isSuperAdmin=false;admNames=[];superAdminName='';if(realtimeChannel){sb.removeChannel(realtimeChannel);realtimeChannel=null;}$('grupoScreen').style.display='flex';$('loginScreen').style.display='none';$('appScreen').style.display='none';$('grupoError').style.display='none';$('grupoLoading').style.display='block';$('grupoList').innerHTML='';$('grupoList').style.display='flex';$('grupoDivider').style.display='block';$('grupoSenhaSection').style.display='none';$('criarGrupoForm').style.display='none';var{data:g}=await sb.from('grupos').select('id,nome,criado_em').order('criado_em',{ascending:false});$('grupoLoading').style.display='none';if(!g||g.length===0){$('grupoList').innerHTML='<div class="empty-state"><span class="emoji">📭</span>Nenhuma pelada cadastrada.<br>Crie abaixo!</div>';}else{var h='';g.forEach(function(x){h+='<button class="grupo-card" onclick="selecionarGrupo(\''+x.id+'\')"><div class="grupo-card-nome">'+x.nome+'</div><div class="grupo-card-id">'+x.id+'</div></button>';});$('grupoList').innerHTML=h;}}
var grupoSelecionadoId=null;
function selecionarGrupo(gid){grupoSelecionadoId=gid;$('grupoError').style.display='none';$('grupoSenhaInput').value='';$('grupoList').style.display='none';$('grupoDivider').style.display='none';$('criarGrupoForm').style.display='none';$('grupoSenhaSection').style.display='block';sb.from('grupos').select('id,nome').eq('id',gid).single().then(function(r){if(r.data)$('grupoSenhaNome').textContent=r.data.nome;});setTimeout(function(){$('grupoSenhaInput').focus();},100);}
function voltarParaListaGrupos(){grupoSelecionadoId=null;$('grupoSenhaSection').style.display='none';$('grupoList').style.display='flex';$('grupoDivider').style.display='block';$('grupoError').style.display='none';}
async function validarSenhaGrupo(){var s=$('grupoSenhaInput').value.trim();if(!s){showGrupoError('Digite a senha.');return;}var{data:g,error:e}=await sb.from('grupos').select('*').eq('id',grupoSelecionadoId).single();if(e||!g){showGrupoError('Grupo não encontrado.');return;}if(s!==g.senha_acesso){showGrupoError('Senha incorreta.');return;}grupoAtual=g;admName=g.admin_name;admPassword=g.admin_password;superAdminName=g.admin_name;var{data:ad}=await sb.from('admins').select('nome,tipo').eq('grupo_id',grupoAtual.id);if(ad&&ad.length>0){admNames=ad.map(function(a){return a.nome;});var se=ad.find(function(a){return a.tipo==='Super';});if(se)superAdminName=se.nome;}else{admNames=[g.admin_name];superAdminName=g.admin_name;}$('grupoSenhaSection').style.display='none';initLogin();}
function toggleCriarGrupo(){var f=$('criarGrupoForm');f.style.display=f.style.display==='none'?'block':'none';}
async function criarGrupo(){var nm=$('novoGrupoNome').value.trim(),id=$('novoGrupoId').value.trim().toUpperCase().replace(/[^A-Z0-9_]/g,''),sa2=$('novoGrupoSenhaAcesso').value.trim(),ad=$('novoGrupoAdm').value.trim(),pw=$('novoGrupoSenha').value.trim();if(!nm||!id||!sa2||!ad||!pw){showGrupoError('Preencha todos.');return;}if(id.length<3||id.length>20){showGrupoError('Código: 3 a 20 chars.');return;}var ac=ad+' (ADM)';var{error:e}=await sb.from('grupos').insert({id:id,nome:nm,admin_name:ac,admin_password:pw,senha_acesso:sa2});if(e){showGrupoError(e.message.includes('duplicate')?'Código já existe.':e.message);return;}await sb.from('jogadores').insert({nome:ac,grupo_id:id});await sb.from('admins').insert({grupo_id:id,nome:ac,senha:pw,tipo:'Super'});showToast('Grupo criado!');$('novoGrupoNome').value='';$('novoGrupoId').value='';$('novoGrupoSenhaAcesso').value='';$('novoGrupoAdm').value='';$('novoGrupoSenha').value='';$('criarGrupoForm').style.display='none';showGrupoScreen();}
function showGrupoError(m){var e=$('grupoError');e.textContent=m;e.style.display='block';}

// === LOGIN ===
async function initLogin(){$('grupoScreen').style.display='none';$('loginScreen').style.display='flex';$('loginGrupoNome').textContent=grupoAtual.nome;var{data:j}=await sb.from('jogadores').select('nome').eq('grupo_id',grupoAtual.id).order('nome');cachedJogadores=j?j.map(function(r){return r.nome;}):[];var{data:p}=await sb.from('peladas').select('*').eq('grupo_id',grupoAtual.id).order('criado_em',{ascending:false});allPeladas=p||[];peladaAtual=allPeladas.length>0?allPeladas[0]:null;var sel=$('loginSelect');sel.innerHTML='<option value="">Selecione seu nome...</option>';sa(cachedJogadores).forEach(function(n){var o=document.createElement('option');o.value=n;o.textContent=dn(n);sel.appendChild(o);});}
function onLoginSelectChange(){var v=$('loginSelect').value;$('passwordGroup').style.display=(admNames.indexOf(v)>-1)?'block':'none';$('loginError').style.display='none';}
async function doLogin(){var v=$('loginSelect').value;if(!v){showLoginError('Selecione.');return;}if(admNames.indexOf(v)>-1){var pw=$('admPassword').value;var{data:ae}=await sb.from('admins').select('nome,senha,tipo').eq('grupo_id',grupoAtual.id).eq('nome',v).single();if(!ae||ae.senha!==pw){showLoginError('Senha incorreta.');return;}finalizeLogin(v,true,ae.tipo==='Super');}else{finalizeLogin(v,false,false);}}
async function finalizeLogin(name,adm,sup){currentUser=name;isAdm=adm;isSuperAdmin=sup;$('headerUserName').textContent=dn(name);$('headerGrupoName').textContent=grupoAtual.nome;$('loginScreen').style.display='none';$('appScreen').style.display='block';$('navAdm').style.display=adm?'flex':'none';$('navFinanceiro').style.display=adm?'flex':'none';logAsync(name,'LOGIN','Entrou');loadHome();}
function doLogout(){if(currentUser)logAsync(currentUser,'LOGOUT','Saiu');if(realtimeChannel){sb.removeChannel(realtimeChannel);realtimeChannel=null;}currentUser=null;isAdm=false;isSuperAdmin=false;$('appScreen').style.display='none';$('admPassword').value='';$('loginSelect').value='';$('passwordGroup').style.display='none';showGrupoScreen();}
function showLoginError(m){var e=$('loginError');e.textContent=m;e.style.display='block';}
function voltarParaGrupos(){$('loginScreen').style.display='none';showGrupoScreen();}
function navigateTo(page){document.querySelectorAll('.page').forEach(function(p){p.classList.remove('active');});$('page'+page).classList.add('active');document.querySelectorAll('.nav-item').forEach(function(n){n.classList.remove('active');});$('nav'+page).classList.add('active');if(page==='Home')loadHome();else if(page==='Votar')loadVotar();else if(page==='Resultados')loadResultados();else if(page==='Adm')loadAdm();else if(page==='AoVivo')loadAoVivo();else if(page==='Financeiro')loadFinanceiro();}

// === HOME ===
async function loadHome(){showSkeleton('homeContent');var{data:p}=await sb.from('peladas').select('*').eq('grupo_id',grupoAtual.id).order('criado_em',{ascending:false});allPeladas=p||[];peladaAtual=allPeladas[0]||null;if(!peladaAtual){$('homeContent').innerHTML='<div class="empty-state"><span class="emoji">📭</span>Nenhuma pelada agendada.</div>';return;}var{data:pr}=await sb.from('presenca').select('jogador').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id);cachedPresentes=pr?pr.map(function(r){return r.jogador;}):[];var{data:vc}=await sb.from('votos').select('id').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id).eq('votante',currentUser).limit(1);renderHome(cachedPresentes,vc&&vc.length>0);}
function renderHome(pres,jv){var el=$('homeContent'),p=peladaAtual;var sb2=p.votacao_aberta?'<span class="badge badge-green">Votação Aberta</span>':p.status==='Encerrada'?'<span class="badge badge-red">Encerrada</span>':p.status==='Realizada'?'<span class="badge badge-blue">Realizada</span>':'<span class="badge badge-gold">Agendada</span>';var po=sa(pres),ph='';if(po.length>0){ph='<div class="mt12" style="display:flex;flex-wrap:wrap;gap:6px;">';po.forEach(function(n){ph+='<span class="badge badge-blue">'+dn(n)+'</span>';});ph+='</div>';}else ph='<div class="text-muted mt8">Nenhum jogador confirmado.</div>';var vs='';if(p.votacao_aberta){vs=jv?'<div class="voted-indicator mt12">✅ Já votou!</div><div style="margin-top:8px;"><button class="btn btn-secondary" onclick="navigateTo(\'Votar\')">✏️ Alterar</button></div>':'<div style="margin-top:12px;"><button class="btn btn-primary" onclick="navigateTo(\'Votar\')">🗳️ Votar</button></div>';}var df=p.data;try{df=new Date(p.data+'T12:00:00').toLocaleDateString('pt-BR');}catch(e){}el.innerHTML='<div class="card status-card'+(p.status==='Encerrada'?' closed':'')+'"><div class="flex-between mb16"><div class="card-title" style="margin-bottom:0;">Pelada da Semana</div>'+sb2+'</div><div class="status-row"><span class="status-label">ID</span><span class="status-value">'+p.id+'</span></div><div class="status-row"><span class="status-label">Data</span><span class="status-value">'+df+'</span></div><div class="status-row"><span class="status-label">Jogadores</span><span class="status-value">'+pres.length+'</span></div><div style="margin-top:12px;"><span class="status-label">Convocados:</span>'+ph+'</div>'+vs+'</div>';}

// === VOTAÇÃO ===
async function loadVotar(){var el=$('votarContent');if(!peladaAtual){el.innerHTML='<div class="empty-state"><span class="emoji">📭</span>Nenhuma pelada.</div>';return;}if(!peladaAtual.votacao_aberta){el.innerHTML='<div class="empty-state"><span class="emoji">🔒</span>Votação fechada.</div>';return;}showSkeleton('votarContent');var{data:pr}=await sb.from('presenca').select('jogador').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id);var pres=pr?pr.map(function(r){return r.jogador;}):[];var{data:ov}=await sb.from('votos').select('*').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id).eq('votante',currentUser);var va=null;if(ov&&ov.length>0){va={goleiro:'',mvp:'',decepcao:'',revelacao:'',selecao:[]};ov.forEach(function(v){if(v.premio==='Goleiro')va.goleiro=v.votado;else if(v.premio==='MVP')va.mvp=v.votado;else if(v.premio==='Decepcao')va.decepcao=v.votado;else if(v.premio==='Revelacao')va.revelacao=v.votado;else if(v.premio==='Selecao')va.selecao.push(v.votado);});}renderVoteForm(pres,va);}
var selecaoSelecionados=[];
function renderVoteForm(pres,va){selecaoSelecionados=[];var isE=va!==null,el=$('votarContent'),po=sa(pres);function bO(sv){var o='<option value="">Selecione...</option>';po.forEach(function(n){o+='<option value="'+n+'"'+(n===sv?' selected':'')+'>'+dn(n)+'</option>';});return o;}var sA=isE?va.selecao:[];selecaoSelecionados=sA.slice();var ch='';po.forEach(function(n){var iS=sA.indexOf(n)>-1;ch+='<div class="chip'+(iS?' selected':'')+(selecaoSelecionados.length>=4&&!iS?' disabled':'')+'" data-name="'+n+'" onclick="toggleSelecao(this)">'+dn(n)+'</div>';});var eb=isE?'<div class="voted-indicator" style="background:var(--blueGlow);border-color:rgba(59,130,246,0.3);color:var(--blue);">✏️ Altere e reenvie.</div>':'';var df=peladaAtual.data;try{df=new Date(peladaAtual.data+'T12:00:00').toLocaleDateString('pt-BR');}catch(e){}el.innerHTML=eb+'<div class="section-desc">Pelada: '+peladaAtual.id+' ('+df+')</div><div class="vote-category"><label><span class="emoji">🧤</span>Goleiro</label><select class="vote-select" id="voteGoleiro">'+bO(isE?va.goleiro:'')+'</select></div><div class="vote-category"><label><span class="emoji">⭐</span>MVP</label><select class="vote-select" id="voteMvp">'+bO(isE?va.mvp:'')+'</select></div><div class="vote-category"><label><span class="emoji">😞</span>Decepção</label><select class="vote-select" id="voteDecepcao">'+bO(isE?va.decepcao:'')+'</select></div><div class="vote-category"><label><span class="emoji">🌟</span>Revelação</label><select class="vote-select" id="voteRevelacao">'+bO(isE?va.revelacao:'')+'</select></div><div class="vote-category"><label><span class="emoji">🏅</span>Seleção (4)</label><div class="selecao-container" id="selecaoContainer">'+ch+'</div><div class="selecao-counter mt8">Selecionados: <span id="selecaoCount">'+selecaoSelecionados.length+'</span>/4</div></div><button class="btn btn-primary mt16" onclick="submitVotos()">'+(isE?'Atualizar':'Enviar')+'</button>';}
function toggleSelecao(c){var n=c.getAttribute('data-name'),x=selecaoSelecionados.indexOf(n);if(x>-1){selecaoSelecionados.splice(x,1);c.classList.remove('selected');}else{if(selecaoSelecionados.length>=4)return;selecaoSelecionados.push(n);c.classList.add('selected');}$('selecaoCount').textContent=selecaoSelecionados.length;document.querySelectorAll('#selecaoContainer .chip').forEach(function(ch){if(selecaoSelecionados.length>=4&&!ch.classList.contains('selected'))ch.classList.add('disabled');else ch.classList.remove('disabled');});}
async function submitVotos(){var g=$('voteGoleiro').value,m=$('voteMvp').value,d=$('voteDecepcao').value,r=$('voteRevelacao').value;if(!g||!m||!d||!r){showToast('Preencha tudo!',true);return;}if(selecaoSelecionados.length!==4){showToast('Selecione 4!',true);return;}await sb.from('votos').delete().eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id).eq('votante',currentUser);var rows=[{pelada_id:peladaAtual.id,votante:currentUser,premio:'Goleiro',votado:g,grupo_id:grupoAtual.id},{pelada_id:peladaAtual.id,votante:currentUser,premio:'MVP',votado:m,grupo_id:grupoAtual.id},{pelada_id:peladaAtual.id,votante:currentUser,premio:'Decepcao',votado:d,grupo_id:grupoAtual.id},{pelada_id:peladaAtual.id,votante:currentUser,premio:'Revelacao',votado:r,grupo_id:grupoAtual.id}];selecaoSelecionados.forEach(function(s){rows.push({pelada_id:peladaAtual.id,votante:currentUser,premio:'Selecao',votado:s,grupo_id:grupoAtual.id});});var{error:e}=await sb.from('votos').insert(rows);if(e){showToast(e.message,true);return;}showToast('Votos registrados! ⚽');logAsync(currentUser,'VOTO',peladaAtual.id);loadVotar();}

// === RESULTADOS ===
function switchResultTab(t){document.querySelectorAll('#resultTabs .tab').forEach(function(tb){tb.classList.remove('active');});['resultadosSemana','resultadosGeral','resultadosArtilharia','resultadosVitorias'].forEach(function(id){$(id).style.display='none';});if(t==='semana'){document.querySelectorAll('#resultTabs .tab')[0].classList.add('active');$('resultadosSemana').style.display='block';}else if(t==='geral'){document.querySelectorAll('#resultTabs .tab')[1].classList.add('active');$('resultadosGeral').style.display='block';}else if(t==='artilharia'){document.querySelectorAll('#resultTabs .tab')[2].classList.add('active');$('resultadosArtilharia').style.display='block';}else if(t==='vitorias'){document.querySelectorAll('#resultTabs .tab')[3].classList.add('active');$('resultadosVitorias').style.display='block';}}
async function loadResultados(){showSkeleton('resultadosSemana');if(peladaAtual){var{data:vs}=await sb.from('votos').select('*').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id);var df=peladaAtual.data;try{df=new Date(peladaAtual.data+'T12:00:00').toLocaleDateString('pt-BR');}catch(e){}renderResultados(buildRanking(vs||[]),'resultadosSemana',peladaAtual.id+' ('+df+')');if(isAdm){$('votosDetalhados').style.display='block';renderVotosDetalhados(vs||[]);}}else{$('resultadosSemana').innerHTML='<div class="empty-state"><span class="emoji">📭</span>Nenhuma pelada.</div>';}var{data:av}=await sb.from('votos').select('*').eq('grupo_id',grupoAtual.id);renderResultados(buildRanking(av||[]),'resultadosGeral','Ranking Geral');var{data:ag}=await sb.from('gols').select('*').eq('grupo_id',grupoAtual.id).eq('gol_contra',false);var am={};(ag||[]).forEach(function(g){am[g.jogador]=(am[g.jogador]||0)+1;});renderRankingSimples(Object.keys(am).map(function(n){return{nome:n,gols:am[n]};}).sort(function(a,b){return b.gols-a.gols;}),'resultadosArtilharia','⚽ Artilharia','gols');var{data:ap}=await sb.from('partidas').select('*').eq('grupo_id',grupoAtual.id).eq('status','Finalizada').neq('vencedor','Empate').neq('vencedor','');var vm={};(ap||[]).forEach(function(p){var tw=p.vencedor==='A'?p.time_a:p.time_b;if(tw)tw.forEach(function(n){if(n)vm[n.trim()]=(vm[n.trim()]||0)+1;});});renderRankingSimples(Object.keys(vm).map(function(n){return{nome:n,vitorias:vm[n]};}).sort(function(a,b){return b.vitorias-a.vitorias;}),'resultadosVitorias','🏆 Vitórias','vitorias');}
function buildRanking(v){var pr=['Goleiro','MVP','Selecao','Decepcao','Revelacao'],r={};pr.forEach(function(p){var c={};v.forEach(function(x){if(x.premio===p)c[x.votado]=(c[x.votado]||0)+1;});r[p]=Object.keys(c).map(function(n){return{nome:n,votos:c[n]};}).sort(function(a,b){return b.votos-a.votos;});});return r;}
function renderRankingSimples(rk,cid,tit,campo){var h='<div class="card"><div class="card-title">'+tit+'</div>';if(!rk||rk.length===0)h+='<div class="text-muted">Sem dados.</div>';else{h+='<ul class="ranking-list">';for(var r=0;r<rk.length&&r<20;r++){var pc=r===0?'gold':r===1?'silver':r===2?'bronze':'normal';h+='<li class="ranking-item"><div class="ranking-pos '+pc+'">'+(r+1)+'</div><div class="ranking-name">'+dn(rk[r].nome)+'</div><div class="ranking-votes">'+rk[r][campo]+'</div></li>';}h+='</ul>';}h+='</div>';$(cid).innerHTML=h;}
function renderResultados(res,cid,tit){var pc=[{key:'Goleiro',emoji:'🧤'},{key:'MVP',emoji:'⭐'},{key:'Selecao',emoji:'🏅'},{key:'Decepcao',emoji:'😞'},{key:'Revelacao',emoji:'🌟'}];var h='<div class="section-desc">'+tit+'</div>';pc.forEach(function(c){var rk=res[c.key]||[];h+='<div class="card"><div class="card-title">'+c.emoji+' '+c.key+'</div>';if(rk.length===0)h+='<div class="text-muted">Sem votos.</div>';else{h+='<ul class="ranking-list">';for(var r=0;r<rk.length&&r<10;r++){var ps=r===0?'gold':r===1?'silver':r===2?'bronze':'normal';h+='<li class="ranking-item"><div class="ranking-pos '+ps+'">'+(r+1)+'</div><div class="ranking-name">'+dn(rk[r].nome)+'</div><div class="ranking-votes">'+rk[r].votos+'</div></li>';}h+='</ul>';}h+='</div>';});$(cid).innerHTML=h;}
function renderVotosDetalhados(v){var el=$('votosDetalhadosContent');if(v.length===0){el.innerHTML='<div class="text-muted">Nenhum voto.</div>';return;}var h='<div style="overflow-x:auto;"><table class="log-table"><tr><th>Votante</th><th>Prêmio</th><th>Votado</th><th>Hora</th></tr>';v.forEach(function(x){var ts=x.timestamp?new Date(x.timestamp).toLocaleString('pt-BR'):'';h+='<tr><td>'+dn(x.votante)+'</td><td>'+x.premio+'</td><td>'+dn(x.votado)+'</td><td class="log-time">'+ts+'</td></tr>';});h+='</table></div>';el.innerHTML=h;}

// === ADM ===
function loadAdm(){if(!isAdm)return;$('admContent').innerHTML='<div class="tabs" id="admTabs"><button class="tab active" onclick="switchAdmTab(\'pelada\')">Pelada</button><button class="tab" onclick="switchAdmTab(\'jogadores\')">Jogadores</button><button class="tab" onclick="switchAdmTab(\'logs\')">Logs</button>'+(isSuperAdmin?'<button class="tab" onclick="switchAdmTab(\'admins\')">Admins</button>':'')+'</div><div id="admTabPelada"></div><div id="admTabJogadores" style="display:none;"></div><div id="admTabLogs" style="display:none;"></div>'+(isSuperAdmin?'<div id="admTabAdmins" style="display:none;"></div>':'');loadAdmPelada();}
function switchAdmTab(t){document.querySelectorAll('#admTabs .tab').forEach(function(tb){tb.classList.remove('active');});['admTabPelada','admTabJogadores','admTabLogs'].forEach(function(id){$(id).style.display='none';});var ae=$('admTabAdmins');if(ae)ae.style.display='none';if(t==='pelada'){document.querySelectorAll('#admTabs .tab')[0].classList.add('active');$('admTabPelada').style.display='block';loadAdmPelada();}if(t==='jogadores'){document.querySelectorAll('#admTabs .tab')[1].classList.add('active');$('admTabJogadores').style.display='block';loadAdmJogadores();}if(t==='logs'){document.querySelectorAll('#admTabs .tab')[2].classList.add('active');$('admTabLogs').style.display='block';loadAdmLogs();}if(t==='admins'&&isSuperAdmin){document.querySelectorAll('#admTabs .tab')[3].classList.add('active');$('admTabAdmins').style.display='block';loadAdmAdmins();}}
async function loadAdmPelada(){showSkeleton('admTabPelada');var{data:p}=await sb.from('peladas').select('*').eq('grupo_id',grupoAtual.id).order('criado_em',{ascending:false});allPeladas=p||[];peladaAtual=allPeladas[0]||null;var po='';allPeladas.forEach(function(p,i){var df=p.data;try{df=new Date(p.data+'T12:00:00').toLocaleDateString('pt-BR');}catch(e){}po+='<option value="'+p.id+'"'+(i===0?' selected':'')+'>'+p.id+' ('+df+') — '+p.status+'</option>';});$('admTabPelada').innerHTML='<div class="card"><div class="card-title">📅 Nova Pelada</div><div class="input-row"><input type="date" id="novaPeladaData"><button class="btn btn-primary" onclick="criarNovaPelada()">Criar</button></div></div>'+(allPeladas.length>0?'<div class="card"><div class="card-title">📋 Gerenciar</div><select class="vote-select mb16" id="admPeladaSelect" onchange="onAdmPeladaSelectChange()">'+po+'</select><div id="admPeladaActions"></div></div><div class="card"><div class="card-title">👥 Presença</div><div id="admPresencaList"></div><button class="btn btn-primary mt12" onclick="salvarPresenca()">Salvar</button></div>':'');if(allPeladas.length>0)loadAdmPeladaDetails(allPeladas[0].id);}
async function loadAdmPeladaDetails(pid){var pel=allPeladas.find(function(p){return p.id===pid;});if(!pel)return;var{data:vt}=await sb.from('votos').select('votante').eq('pelada_id',pid).eq('grupo_id',grupoAtual.id);var uq={};(vt||[]).forEach(function(v){uq[v.votante]=true;});var qjv=Object.keys(uq);var ae=$('admPeladaActions');var h='<div class="flex-between mb16"><span class="text-muted">Status: '+pel.status+'</span>';if(!pel.votacao_aberta&&pel.status!=='Encerrada')h+='<button class="btn btn-primary" style="width:auto;padding:10px 20px;font-size:13px;" onclick="abrirVotacao(\''+pid+'\')">Abrir Votação</button>';else if(pel.votacao_aberta)h+='<button class="btn btn-danger" style="width:auto;padding:10px 20px;font-size:13px;" onclick="fecharVotacao(\''+pid+'\')">Fechar Votação</button>';h+='</div>';if(qjv.length>0)h+='<div class="text-muted" style="font-size:12px;">Votaram ('+qjv.length+'): '+sa(qjv).map(dn).join(', ')+'</div>';if(ae)ae.innerHTML=h;var{data:pr}=await sb.from('presenca').select('jogador').eq('pelada_id',pid).eq('grupo_id',grupoAtual.id);var pl=(pr||[]).map(function(r){return r.jogador;});var{data:jg}=await sb.from('jogadores').select('nome').eq('grupo_id',grupoAtual.id).order('nome');var jl=(jg||[]).map(function(r){return r.nome;});var le=$('admPresencaList');if(le){var jo=sa(jl),lh='<div class="checkbox-list">';jo.forEach(function(n,i){lh+='<div class="checkbox-item"><input type="checkbox" id="pres_'+i+'" value="'+n+'"'+(pl.indexOf(n)>-1?' checked':'')+'><label for="pres_'+i+'">'+dn(n)+'</label></div>';});lh+='</div>';le.innerHTML=lh;}}
function onAdmPeladaSelectChange(){loadAdmPeladaDetails($('admPeladaSelect').value);}
async function criarNovaPelada(){var d=$('novaPeladaData').value;if(!d){showToast('Data!',true);return;}var{data:nid}=await sb.rpc('next_pelada_id_grupo',{p_grupo_id:grupoAtual.id});var{error:e}=await sb.from('peladas').insert({id:nid,data:d,status:'Agendada',votacao_aberta:false,grupo_id:grupoAtual.id});if(e){showToast(e.message,true);return;}showToast('Criada: '+nid);logAsync(currentUser,'CRIAR_PELADA',nid);loadAdmPelada();}
async function abrirVotacao(pid){await sb.from('peladas').update({status:'Realizada',votacao_aberta:true}).eq('id',pid).eq('grupo_id',grupoAtual.id);showToast('Aberta!');logAsync(currentUser,'ABRIR_VOTACAO',pid);loadAdmPelada();}
async function fecharVotacao(pid){await sb.from('peladas').update({status:'Encerrada',votacao_aberta:false}).eq('id',pid).eq('grupo_id',grupoAtual.id);showToast('Fechada!');logAsync(currentUser,'FECHAR_VOTACAO',pid);loadAdmPelada();}
async function salvarPresenca(){var pid=$('admPeladaSelect').value;var cb=document.querySelectorAll('#admPresencaList input[type="checkbox"]');var pr=[];cb.forEach(function(c){if(c.checked)pr.push(c.value);});await sb.from('presenca').delete().eq('pelada_id',pid).eq('grupo_id',grupoAtual.id);if(pr.length>0)await sb.from('presenca').insert(pr.map(function(j){return{pelada_id:pid,jogador:j,grupo_id:grupoAtual.id};}));showToast(pr.length+' marcados.');logAsync(currentUser,'PRESENCA',pid);}
async function loadAdmJogadores(){showSkeleton('admTabJogadores');var{data:jg}=await sb.from('jogadores').select('nome').eq('grupo_id',grupoAtual.id).order('nome');var jl=(jg||[]).map(function(r){return r.nome;});cachedJogadores=jl;var jo=sa(jl);var h='<div class="card"><div class="card-title">➕ Jogador</div><div class="input-row"><input type="text" id="novoJogadorNome" placeholder="Nome"><button class="btn btn-primary" onclick="adicionarJogador()">Add</button></div></div><div class="card"><div class="card-title">📋 Jogadores ('+jl.length+')</div>';jo.forEach(function(n){var isA=admNames.indexOf(n)>-1;h+='<div class="flex-between" style="padding:8px 0;border-bottom:1px solid rgba(36,48,73,0.3);"><span style="font-size:14px;">'+dn(n)+(isA?' <span class="badge badge-purple" style="font-size:9px;">ADM</span>':'')+'</span>';if(!isA)h+='<button class="btn-logout" style="color:var(--red);border-color:var(--red);font-size:11px;" onclick="removerJogador(\''+n.replace(/'/g,"\\'")+'\')">✕</button>';h+='</div>';});h+='</div>';$('admTabJogadores').innerHTML=h;}
async function adicionarJogador(){var n=$('novoJogadorNome').value.trim();if(!n){showToast('Nome!',true);return;}var{error:e}=await sb.from('jogadores').insert({nome:n,grupo_id:grupoAtual.id});if(e){showToast(e.message.includes('duplicate')?'Já existe.':e.message,true);return;}showToast('OK.');logAsync(currentUser,'ADD_JOGADOR',n);loadAdmJogadores();}
async function removerJogador(n){if(admNames.indexOf(n)>-1){showToast('Remova ADM primeiro.',true);return;}if(!confirm('Remover '+dn(n)+'?'))return;await sb.from('jogadores').delete().eq('nome',n).eq('grupo_id',grupoAtual.id);showToast('Removido.');logAsync(currentUser,'REMOVER_JOGADOR',n);loadAdmJogadores();}
async function loadAdmLogs(){showSkeleton('admTabLogs');var{data:l}=await sb.from('logs').select('*').eq('grupo_id',grupoAtual.id).order('timestamp',{ascending:false}).limit(100);if(!l||l.length===0){$('admTabLogs').innerHTML='<div class="empty-state"><span class="emoji">📋</span>Vazio.</div>';return;}var h='<div class="card"><div class="card-title">📋 Logs</div><div style="overflow-x:auto;"><table class="log-table"><tr><th>Usuário</th><th>Ação</th><th>Detalhes</th><th>Hora</th></tr>';l.forEach(function(x){var ts=x.timestamp?new Date(x.timestamp).toLocaleString('pt-BR'):'';h+='<tr><td>'+dn(x.usuario)+'</td><td>'+x.acao+'</td><td>'+x.detalhes+'</td><td class="log-time">'+ts+'</td></tr>';});h+='</table></div></div>';$('admTabLogs').innerHTML=h;}
async function loadAdmAdmins(){if(!isSuperAdmin)return;showSkeleton('admTabAdmins');var{data:al}=await sb.from('admins').select('nome,tipo').eq('grupo_id',grupoAtual.id).order('tipo',{ascending:false});al=al||[];var{data:jg}=await sb.from('jogadores').select('nome').eq('grupo_id',grupoAtual.id).order('nome');var jl=(jg||[]).map(function(r){return r.nome;});var as={};al.forEach(function(a){as[a.nome]=true;});var h='<div class="card"><div class="card-title">👑 Add ADM</div><div style="margin-bottom:8px;"><select class="vote-select" id="novoAdminNome"><option value="">Selecione...</option>';sa(jl).forEach(function(n){if(!as[n])h+='<option value="'+n+'">'+dn(n)+'</option>';});h+='</select></div><div class="input-row"><input type="text" id="novoAdminSenha" placeholder="Senha"><button class="btn btn-primary" onclick="addAdmin()">Add</button></div></div><div class="card"><div class="card-title">🔐 ADMs ('+al.length+')</div>';al.forEach(function(a){var tl=a.tipo==='Super'?'👑 Super':'🛡️ Admin';var tc=a.tipo==='Super'?'var(--goldGlow)':'var(--purpleGlow)';var tf=a.tipo==='Super'?'var(--gold)':'var(--purple)';h+='<div style="display:flex;align-items:center;justify-content:space-between;padding:12px 0;border-bottom:1px solid rgba(36,48,73,0.3);"><div style="flex:1;"><div style="font-size:14px;font-weight:500;">'+dn(a.nome)+'</div><div style="display:inline-block;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:600;margin-top:2px;background:'+tc+';color:'+tf+';">'+tl+'</div></div><div style="display:flex;gap:6px;"><button style="padding:6px 10px;border-radius:8px;font-size:11px;font-weight:600;cursor:pointer;font-family:inherit;border:1px solid var(--blue);background:transparent;color:var(--blue);" onclick="editarSenhaAdmin(\''+a.nome.replace(/'/g,"\\'")+'\')">✏️</button>';if(a.tipo!=='Super')h+='<button style="padding:6px 10px;border-radius:8px;font-size:11px;font-weight:600;cursor:pointer;font-family:inherit;border:1px solid var(--red);background:transparent;color:var(--red);" onclick="removeAdmin(\''+a.nome.replace(/'/g,"\\'")+'\')">✕</button>';h+='</div></div>';});h+='</div>';$('admTabAdmins').innerHTML=h;}
async function addAdmin(){var n=$('novoAdminNome').value,s=$('novoAdminSenha').value.trim();if(!n){showToast('Selecione!',true);return;}if(!s){showToast('Senha!',true);return;}var{error:e}=await sb.from('admins').insert({grupo_id:grupoAtual.id,nome:n,senha:s,tipo:'Admin'});if(e){showToast(e.message.includes('duplicate')?'Já é ADM.':e.message,true);return;}admNames.push(n);showToast(dn(n)+' é ADM.');logAsync(currentUser,'ADD_ADMIN',n);loadAdmAdmins();}
async function removeAdmin(n){if(!confirm('Remover '+dn(n)+' como ADM?'))return;await sb.from('admins').delete().eq('grupo_id',grupoAtual.id).eq('nome',n);var i=admNames.indexOf(n);if(i>-1)admNames.splice(i,1);showToast('Removido.');logAsync(currentUser,'REMOVE_ADMIN',n);loadAdmAdmins();}
async function editarSenhaAdmin(n){var ns=prompt('Nova senha para '+dn(n)+':');if(!ns||!ns.trim())return;await sb.from('admins').update({senha:ns.trim()}).eq('grupo_id',grupoAtual.id).eq('nome',n);showToast('Atualizada.');logAsync(currentUser,'ALTERAR_SENHA',n);}

// === FINANCEIRO ===
async function loadFinanceiro(){if(!isAdm)return;var el=$('financeiroContent');el.innerHTML='<div class="tabs" id="finTabs"><button class="tab active" onclick="switchFinTab(\'pagamentos\')">Pagamentos</button><button class="tab" onclick="switchFinTab(\'mensalistas\')">Mensalistas</button><button class="tab" onclick="switchFinTab(\'despesas\')">Despesas</button><button class="tab" onclick="switchFinTab(\'balanco\')">Balanço</button><button class="tab" onclick="switchFinTab(\'devedores\')">Devedores</button><button class="tab" onclick="switchFinTab(\'config\')">Config</button></div><div id="finTabPagamentos"></div><div id="finTabMensalistas" style="display:none;"></div><div id="finTabDespesas" style="display:none;"></div><div id="finTabBalanco" style="display:none;"></div><div id="finTabDevedores" style="display:none;"></div><div id="finTabConfig" style="display:none;"></div>';var{data:cfg}=await sb.from('financeiro_config').select('*').eq('grupo_id',grupoAtual.id).single();finConfig=cfg;finMesSelecionado=mesAtual();loadFinPagamentos();}
function switchFinTab(t){document.querySelectorAll('#finTabs .tab').forEach(function(tb){tb.classList.remove('active');});['finTabPagamentos','finTabMensalistas','finTabDespesas','finTabBalanco','finTabDevedores','finTabConfig'].forEach(function(id){var e=$(id);if(e)e.style.display='none';});var tabs=document.querySelectorAll('#finTabs .tab');var map={pagamentos:0,mensalistas:1,despesas:2,balanco:3,devedores:4,config:5};if(tabs[map[t]])tabs[map[t]].classList.add('active');var tid='finTab'+t.charAt(0).toUpperCase()+t.slice(1);var te=$(tid);if(te)te.style.display='block';if(t==='pagamentos')loadFinPagamentos();else if(t==='mensalistas')loadFinMensalistas();else if(t==='despesas')loadFinDespesas();else if(t==='balanco')loadFinBalanco();else if(t==='devedores')loadFinDevedores();else if(t==='config')loadFinConfig();}

// FIN: CONFIG
async function loadFinConfig(){var el=$('finTabConfig');var c=finConfig;el.innerHTML='<div class="card"><div class="card-title">⚙️ Config Financeiro</div><div class="vote-category"><label>Mensalidade (R$)</label><input type="number" class="vote-select" id="finCfgM" value="'+(c?c.valor_mensalidade:150)+'" step="0.01"></div><div class="vote-category"><label>Diária (R$)</label><input type="number" class="vote-select" id="finCfgD" value="'+(c?c.valor_diaria:30)+'" step="0.01"></div><div class="vote-category"><label>Mês Início</label><input type="month" class="vote-select" id="finCfgI" value="'+(c?c.mes_inicio:mesAtual())+'"></div><div class="vote-category"><label>Saldo Inicial (R$)</label><input type="number" class="vote-select" id="finCfgS" value="'+(c?c.saldo_inicial:0)+'" step="0.01"></div><button class="btn btn-primary" onclick="salvarFinConfig()">Salvar</button></div>';}
async function salvarFinConfig(){var vm=parseFloat($('finCfgM').value)||0,vd=parseFloat($('finCfgD').value)||0,mi=$('finCfgI').value,si=parseFloat($('finCfgS').value)||0;if(!mi){showToast('Mês!',true);return;}if(finConfig){await sb.from('financeiro_config').update({valor_mensalidade:vm,valor_diaria:vd,mes_inicio:mi,saldo_inicial:si,atualizado_em:new Date().toISOString()}).eq('grupo_id',grupoAtual.id);}else{await sb.from('financeiro_config').insert({grupo_id:grupoAtual.id,valor_mensalidade:vm,valor_diaria:vd,mes_inicio:mi,saldo_inicial:si});}var{data:cfg}=await sb.from('financeiro_config').select('*').eq('grupo_id',grupoAtual.id).single();finConfig=cfg;showToast('Salvo!');logAsync(currentUser,'FIN_CONFIG','M:'+vm+' D:'+vd+' I:'+mi);}

// FIN: MENSALISTAS
async function loadFinMensalistas(){var el=$('finTabMensalistas');showSkeleton('finTabMensalistas');var{data:jg}=await sb.from('jogadores').select('nome').eq('grupo_id',grupoAtual.id).order('nome');var jl=(jg||[]).map(function(r){return r.nome;});var{data:ms}=await sb.from('mensalistas').select('*').eq('grupo_id',grupoAtual.id);ms=ms||[];var h='<div class="card"><div class="card-title">➕ Novo Mensalista</div><div style="margin-bottom:8px;"><select class="vote-select" id="finNM"><option value="">Jogador...</option>';sa(jl).forEach(function(n){h+='<option value="'+n+'">'+dn(n)+'</option>';});h+='</select></div><div class="vote-category"><label>A partir de</label><input type="month" class="vote-select" id="finMI" value="'+mesAtual()+'"></div><button class="btn btn-primary" onclick="addMens()">Adicionar</button></div>';var at=ms.filter(function(m){return!m.mes_fim||m.mes_fim>=mesAtual();});h+='<div class="card"><div class="card-title">📋 Mensalistas Ativos ('+at.length+')</div>';if(at.length===0)h+='<div class="text-muted">Nenhum.</div>';else at.forEach(function(m){h+='<div class="flex-between" style="padding:10px 0;border-bottom:1px solid rgba(36,48,73,0.3);"><div><div style="font-size:14px;font-weight:500;">'+dn(m.jogador)+'</div><div class="text-muted" style="font-size:11px;">Desde '+fmtMes(m.mes_inicio)+(m.mes_fim?' até '+fmtMes(m.mes_fim):'')+'</div></div><button style="padding:6px 10px;border-radius:8px;font-size:11px;font-weight:600;cursor:pointer;font-family:inherit;border:1px solid var(--red);background:transparent;color:var(--red);" onclick="encMens('+m.id+')">Encerrar</button></div>';});h+='</div>';el.innerHTML=h;}
async function addMens(){var n=$('finNM').value,mi=$('finMI').value;if(!n){showToast('Jogador!',true);return;}if(!mi){showToast('Mês!',true);return;}var{error:e}=await sb.from('mensalistas').insert({grupo_id:grupoAtual.id,jogador:n,mes_inicio:mi,mes_fim:null});if(e){showToast(e.message.includes('duplicate')?'Já é mensalista.':e.message,true);return;}showToast(dn(n)+' mensalista desde '+fmtMes(mi));logAsync(currentUser,'ADD_MENS',n+' '+mi);loadFinMensalistas();}
async function encMens(id){var mf=prompt('Último mês (AAAA-MM):',mesAtual());if(!mf)return;if(!/^\d{4}-\d{2}$/.test(mf)){showToast('Formato AAAA-MM!',true);return;}await sb.from('mensalistas').update({mes_fim:mf}).eq('id',id);showToast('Encerrado em '+fmtMes(mf));logAsync(currentUser,'ENC_MENS','ID '+id);loadFinMensalistas();}

// FIN: PAGAMENTOS
async function loadFinPagamentos(){var el=$('finTabPagamentos');showSkeleton('finTabPagamentos');if(!finConfig){el.innerHTML='<div class="empty-state"><span class="emoji">⚙️</span>Configure primeiro (aba Config).</div>';return;}var mes=finMesSelecionado||mesAtual();var meses=gerarMeses(finConfig.mes_inicio,mesAtual());var{data:ms}=await sb.from('mensalistas').select('*').eq('grupo_id',grupoAtual.id);ms=ms||[];var{data:pg}=await sb.from('pagamentos').select('*').eq('grupo_id',grupoAtual.id).eq('mes',mes);pg=pg||[];var{data:pa}=await sb.from('presenca').select('jogador,pelada_id').eq('grupo_id',grupoAtual.id);pa=pa||[];var{data:pl}=await sb.from('peladas').select('id,data').eq('grupo_id',grupoAtual.id);pl=pl||[];
var mm=[];ms.forEach(function(m){if(m.mes_inicio<=mes&&(!m.mes_fim||m.mes_fim>=mes))mm.push(m.jogador);});
var pdm=pl.filter(function(p){return p.data&&p.data.substring(0,7)===mes;});var pids=pdm.map(function(p){return p.id;});
var dm={};pa.forEach(function(pr){if(pids.indexOf(pr.pelada_id)===-1)return;if(mm.indexOf(pr.jogador)>-1)return;if(!dm[pr.jogador])dm[pr.jogador]=[];dm[pr.jogador].push(pr.pelada_id);});
var pm={};pg.forEach(function(p){pm[p.jogador+'|'+p.tipo+'|'+(p.pelada_id||'')]=p;});
var mo='';meses.forEach(function(m){mo+='<option value="'+m+'"'+(m===mes?' selected':'')+'>'+fmtMes(m)+'</option>';});
var h='<div class="card"><div class="flex-between"><div class="card-title" style="margin-bottom:0;">💰 Pagamentos</div><select class="vote-select" style="width:140px;margin-bottom:0;" onchange="finMesSelecionado=this.value;loadFinPagamentos();">'+mo+'</select></div></div>';
h+='<div class="card"><div class="card-title">📋 Mensalistas ('+mm.length+')</div>';if(mm.length===0)h+='<div class="text-muted">Nenhum neste mês.</div>';else sa(mm).forEach(function(n){var k=n+'|mensalidade|';var p=pm[k];var vc=p?p.valor_cobrado:finConfig.valor_mensalidade;var vp=p?p.valor_pago:0;var pg2=p?p.pago:false;h+='<div style="padding:10px 0;border-bottom:1px solid rgba(36,48,73,0.3);"><div class="flex-between"><span style="font-size:14px;">'+dn(n)+'</span><span style="font-size:12px;color:'+(pg2?'var(--green)':'var(--red)')+';">'+(pg2?'✅ '+fmtBRL(vp):'❌ '+fmtBRL(vp)+'/'+fmtBRL(vc))+'</span></div><div style="display:flex;gap:6px;margin-top:6px;">';if(!pg2)h+='<button class="btn btn-primary" style="width:auto;padding:6px 14px;font-size:12px;" onclick="mPago(\''+n.replace(/'/g,"\\'")+'\',\'mensalidade\',null,'+vc+')">Pago</button>';h+='<button class="btn btn-secondary" style="width:auto;padding:6px 14px;font-size:12px;" onclick="ePag(\''+n.replace(/'/g,"\\'")+'\',\'mensalidade\',null)">Editar</button>';if(pg2)h+='<button class="btn btn-secondary" style="width:auto;padding:6px 14px;font-size:12px;color:var(--red);border-color:var(--red);" onclick="dPago(\''+n.replace(/'/g,"\\'")+'\',\'mensalidade\',null)">Desfazer</button>';h+='</div></div>';});h+='</div>';
var dk=Object.keys(dm);h+='<div class="card"><div class="card-title">🎫 Diaristas ('+dk.length+')</div>';if(dk.length===0)h+='<div class="text-muted">Nenhum neste mês.</div>';else sa(dk).forEach(function(n){dm[n].forEach(function(pid){var k=n+'|diaria|'+pid;var p=pm[k];var vc=p?p.valor_cobrado:finConfig.valor_diaria;var vp=p?p.valor_pago:0;var pg2=p?p.pago:false;var pr=pdm.find(function(x){return x.id===pid;});var df=pid;try{df=new Date(pr.data+'T12:00:00').toLocaleDateString('pt-BR');}catch(e){}h+='<div style="padding:8px 0;border-bottom:1px solid rgba(36,48,73,0.3);"><div class="flex-between"><span style="font-size:13px;">'+dn(n)+' <span class="text-muted">('+df+')</span></span><span style="font-size:11px;color:'+(pg2?'var(--green)':'var(--red)')+';">'+(pg2?'✅ '+fmtBRL(vp):'❌ '+fmtBRL(vp)+'/'+fmtBRL(vc))+'</span></div><div style="display:flex;gap:6px;margin-top:4px;">';if(!pg2)h+='<button class="btn btn-primary" style="width:auto;padding:4px 10px;font-size:11px;" onclick="mPago(\''+n.replace(/'/g,"\\'")+'\',\'diaria\',\''+pid+'\','+vc+')">Pago</button>';h+='<button class="btn btn-secondary" style="width:auto;padding:4px 10px;font-size:11px;" onclick="ePag(\''+n.replace(/'/g,"\\'")+'\',\'diaria\',\''+pid+'\')">Editar</button>';if(pg2)h+='<button class="btn btn-secondary" style="width:auto;padding:4px 10px;font-size:11px;color:var(--red);border-color:var(--red);" onclick="dPago(\''+n.replace(/'/g,"\\'")+'\',\'diaria\',\''+pid+'\')">Desfazer</button>';h+='</div></div>';});});h+='</div>';el.innerHTML=h;}
async function mPago(j,t,pid,vc){var mes=finMesSelecionado;var q=sb.from('pagamentos').select('id').eq('grupo_id',grupoAtual.id).eq('jogador',j).eq('mes',mes).eq('tipo',t);if(pid)q=q.eq('pelada_id',pid);else q=q.is('pelada_id',null);var{data:ex}=await q;if(ex&&ex.length>0){await sb.from('pagamentos').update({pago:true,valor_pago:vc,valor_cobrado:vc,atualizado_em:new Date().toISOString()}).eq('id',ex[0].id);}else{await sb.from('pagamentos').insert({grupo_id:grupoAtual.id,jogador:j,mes:mes,tipo:t,pelada_id:pid,valor_cobrado:vc,valor_pago:vc,pago:true});}showToast('Pago!');loadFinPagamentos();}
async function dPago(j,t,pid){var mes=finMesSelecionado;var q=sb.from('pagamentos').select('id').eq('grupo_id',grupoAtual.id).eq('jogador',j).eq('mes',mes).eq('tipo',t);if(pid)q=q.eq('pelada_id',pid);else q=q.is('pelada_id',null);var{data:ex}=await q;if(ex&&ex.length>0)await sb.from('pagamentos').update({pago:false,valor_pago:0,atualizado_em:new Date().toISOString()}).eq('id',ex[0].id);showToast('Desfeito.');loadFinPagamentos();}
async function ePag(j,t,pid){var mes=finMesSelecionado;var dv=t==='mensalidade'?finConfig.valor_mensalidade:finConfig.valor_diaria;var nvc=prompt('Valor cobrado de '+dn(j)+' (R$):',dv);if(nvc===null)return;nvc=parseFloat(nvc);if(isNaN(nvc)){showToast('Inválido!',true);return;}var nvp=prompt('Valor pago (R$):',nvc);if(nvp===null)return;nvp=parseFloat(nvp);if(isNaN(nvp)){showToast('Inválido!',true);return;}var pg=nvp>=nvc;var q=sb.from('pagamentos').select('id').eq('grupo_id',grupoAtual.id).eq('jogador',j).eq('mes',mes).eq('tipo',t);if(pid)q=q.eq('pelada_id',pid);else q=q.is('pelada_id',null);var{data:ex}=await q;if(ex&&ex.length>0){await sb.from('pagamentos').update({valor_cobrado:nvc,valor_pago:nvp,pago:pg,atualizado_em:new Date().toISOString()}).eq('id',ex[0].id);}else{await sb.from('pagamentos').insert({grupo_id:grupoAtual.id,jogador:j,mes:mes,tipo:t,pelada_id:pid,valor_cobrado:nvc,valor_pago:nvp,pago:pg});}showToast('Atualizado!');loadFinPagamentos();}

// FIN: DESPESAS
async function loadFinDespesas(){var el=$('finTabDespesas');showSkeleton('finTabDespesas');var{data:ds}=await sb.from('despesas').select('*').eq('grupo_id',grupoAtual.id).order('mes_competencia',{ascending:false});ds=ds||[];var cats={campo:'Campo',goleiros:'Goleiros',confraternizacoes:'Confraternizações',material_esportivo:'Material Esportivo',outros:'Outros'};var co='';Object.keys(cats).forEach(function(k){co+='<option value="'+k+'">'+cats[k]+'</option>';});var h='<div class="card"><div class="card-title">➕ Nova Despesa</div><div class="vote-category"><label>Categoria</label><select class="vote-select" id="finDC">'+co+'</select></div><div class="vote-category"><label>Mês Competência</label><input type="month" class="vote-select" id="finDM" value="'+mesAtual()+'"></div><div class="vote-category"><label>Valor (R$)</label><input type="number" class="vote-select" id="finDV" step="0.01"></div><div class="vote-category"><label>Descrição</label><input type="text" class="vote-select" id="finDD" placeholder="Ex: Aluguel campo"></div><button class="btn btn-primary" onclick="addDesp()">Adicionar</button></div>';h+='<div class="card"><div class="card-title">📋 Despesas ('+ds.length+')</div>';if(ds.length===0)h+='<div class="text-muted">Nenhuma.</div>';else ds.forEach(function(d){h+='<div class="flex-between" style="padding:10px 0;border-bottom:1px solid rgba(36,48,73,0.3);"><div><div style="font-size:13px;font-weight:500;">'+(cats[d.categoria]||d.categoria)+'</div><div class="text-muted" style="font-size:11px;">'+fmtMes(d.mes_competencia)+(d.descricao?' — '+d.descricao:'')+'</div></div><div style="display:flex;align-items:center;gap:8px;"><span style="font-size:14px;font-weight:600;color:var(--red);">'+fmtBRL(d.valor)+'</span><button style="padding:4px 8px;border-radius:6px;font-size:11px;cursor:pointer;font-family:inherit;border:1px solid var(--red);background:transparent;color:var(--red);" onclick="remDesp('+d.id+')">✕</button></div></div>';});h+='</div>';el.innerHTML=h;}
async function addDesp(){var c=$('finDC').value,m=$('finDM').value,v=parseFloat($('finDV').value),d=$('finDD').value.trim();if(!m||!v){showToast('Preencha!',true);return;}await sb.from('despesas').insert({grupo_id:grupoAtual.id,mes_competencia:m,categoria:c,valor:v,descricao:d});showToast('Adicionada!');logAsync(currentUser,'ADD_DESP',c+' '+m+' '+v);loadFinDespesas();}
async function remDesp(id){if(!confirm('Remover?'))return;await sb.from('despesas').delete().eq('id',id);showToast('Removida.');loadFinDespesas();}

// FIN: BALANÇO
async function loadFinBalanco(){var el=$('finTabBalanco');showSkeleton('finTabBalanco');if(!finConfig){el.innerHTML='<div class="empty-state"><span class="emoji">⚙️</span>Configure primeiro.</div>';return;}var meses=gerarMeses(finConfig.mes_inicio,mesAtual());var{data:pg}=await sb.from('pagamentos').select('*').eq('grupo_id',grupoAtual.id);pg=pg||[];var{data:ds}=await sb.from('despesas').select('*').eq('grupo_id',grupoAtual.id);ds=ds||[];var sa2=finConfig.saldo_inicial;var h='<div class="card"><div class="card-title">📊 Balanço</div><div style="overflow-x:auto;"><table class="log-table"><tr><th>Mês</th><th>Saldo Ini</th><th>Rec. Mens.</th><th>Rec. Diár.</th><th>Despesas</th><th>Fluxo</th><th>Saldo Fim</th></tr>';meses.forEach(function(mes){var rm=0,rd=0,dt=0;pg.forEach(function(p){if(p.mes===mes&&p.pago){if(p.tipo==='mensalidade')rm+=Number(p.valor_pago);else rd+=Number(p.valor_pago);}});ds.forEach(function(d){if(d.mes_competencia===mes)dt+=Number(d.valor);});var fl=rm+rd-dt;var si=sa2;var sf=si+fl;sa2=sf;h+='<tr><td style="font-weight:600;">'+fmtMes(mes)+'</td><td>'+fmtBRL(si)+'</td><td style="color:var(--green);">'+fmtBRL(rm)+'</td><td style="color:var(--green);">'+fmtBRL(rd)+'</td><td style="color:var(--red);">'+fmtBRL(dt)+'</td><td style="color:'+(fl>=0?'var(--green)':'var(--red)')+';font-weight:600;">'+fmtBRL(fl)+'</td><td style="color:'+(sf>=0?'var(--green)':'var(--red)')+';font-weight:600;">'+fmtBRL(sf)+'</td></tr>';});h+='</table></div></div>';el.innerHTML=h;}

// FIN: DEVEDORES
async function loadFinDevedores(){var el=$('finTabDevedores');showSkeleton('finTabDevedores');if(!finConfig){el.innerHTML='<div class="empty-state"><span class="emoji">⚙️</span>Configure primeiro.</div>';return;}var meses=gerarMeses(finConfig.mes_inicio,mesAtual());var{data:ms}=await sb.from('mensalistas').select('*').eq('grupo_id',grupoAtual.id);ms=ms||[];var{data:pg}=await sb.from('pagamentos').select('*').eq('grupo_id',grupoAtual.id);pg=pg||[];var{data:pa}=await sb.from('presenca').select('jogador,pelada_id').eq('grupo_id',grupoAtual.id);pa=pa||[];var{data:pl}=await sb.from('peladas').select('id,data').eq('grupo_id',grupoAtual.id);pl=pl||[];var pm={};pg.forEach(function(p){pm[p.jogador+'|'+p.tipo+'|'+p.mes+'|'+(p.pelada_id||'')]=p;});var devs=[];meses.forEach(function(mes){ms.forEach(function(m){if(m.mes_inicio<=mes&&(!m.mes_fim||m.mes_fim>=mes)){var k=m.jogador+'|mensalidade|'+mes+'|';var p=pm[k];var vc=p?Number(p.valor_cobrado):finConfig.valor_mensalidade;var vp=p?Number(p.valor_pago):0;if(!p||!p.pago)devs.push({jogador:m.jogador,tipo:'Mensalidade',mes:mes,cobrado:vc,pago:vp,pendente:vc-vp});}});var pdm=pl.filter(function(p){return p.data&&p.data.substring(0,7)===mes;});var pids=pdm.map(function(p){return p.id;});var mmn=[];ms.forEach(function(m){if(m.mes_inicio<=mes&&(!m.mes_fim||m.mes_fim>=mes))mmn.push(m.jogador);});pa.forEach(function(pr){if(pids.indexOf(pr.pelada_id)===-1)return;if(mmn.indexOf(pr.jogador)>-1)return;var k=pr.jogador+'|diaria|'+mes+'|'+pr.pelada_id;var p=pm[k];var vc=p?Number(p.valor_cobrado):finConfig.valor_diaria;var vp=p?Number(p.valor_pago):0;if(!p||!p.pago){var pf=pdm.find(function(x){return x.id===pr.pelada_id;});var df=pr.pelada_id;try{df=new Date(pf.data+'T12:00:00').toLocaleDateString('pt-BR');}catch(e){}devs.push({jogador:pr.jogador,tipo:'Diária ('+df+')',mes:mes,cobrado:vc,pago:vp,pendente:vc-vp});}});});devs.sort(function(a,b){var c=a.jogador.localeCompare(b.jogador);return c!==0?c:a.mes.localeCompare(b.mes);});var h='<div class="card"><div class="card-title">🚨 Devedores ('+devs.length+')</div>';if(devs.length===0)h+='<div style="text-align:center;padding:20px;color:var(--green);font-size:14px;">✅ Tudo em dia!</div>';else{h+='<div style="overflow-x:auto;"><table class="log-table"><tr><th>Jogador</th><th>Tipo</th><th>Mês</th><th>Cobrado</th><th>Pago</th><th>Pendente</th></tr>';devs.forEach(function(d){h+='<tr><td style="font-weight:500;">'+dn(d.jogador)+'</td><td>'+d.tipo+'</td><td>'+fmtMes(d.mes)+'</td><td>'+fmtBRL(d.cobrado)+'</td><td>'+fmtBRL(d.pago)+'</td><td style="color:var(--red);font-weight:600;">'+fmtBRL(d.pendente)+'</td></tr>';});h+='</table></div>';}h+='</div>';el.innerHTML=h;}

// === AO VIVO ===
var aoVivoPresentes=[],teamPicks={};
async function loadAoVivo(){var el=$('aoVivoContent');if(!peladaAtual){el.innerHTML='<div class="empty-state"><span class="emoji">📭</span>Nenhuma pelada.</div>';return;}showSkeleton('aoVivoContent');var{data:pr}=await sb.from('peladas').select('*').eq('id',peladaAtual.id).eq('grupo_id',grupoAtual.id).single();if(pr)peladaAtual=pr;if(peladaAtual.status==='Realizada'||peladaAtual.status==='Encerrada'){var{data:pts}=await sb.from('partidas').select('*').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id).order('numero');var fn=(pts||[]).filter(function(p){return p.status==='Finalizada';});if(fn.length>0){var rh='<div class="card"><div class="card-title">📋 Partidas</div>';fn.forEach(function(p){var vl=p.vencedor==='A'?'🔵 A':(p.vencedor==='B'?'🟠 B':'🤝 Emp');rh+='<div class="flex-between" style="padding:8px 0;border-bottom:1px solid rgba(36,48,73,0.3);font-size:13px;"><span>P'+p.numero+'</span><span style="font-weight:600;">'+p.placar_a+' x '+p.placar_b+'</span><span class="text-muted">'+vl+'</span></div>';});rh+='</div>';el.innerHTML=rh+'<div class="empty-state"><span class="emoji">✅</span>Encerrada.</div>';}else el.innerHTML='<div class="empty-state"><span class="emoji">✅</span>Encerrada.</div>';if(realtimeChannel){sb.removeChannel(realtimeChannel);realtimeChannel=null;}return;}var{data:ps}=await sb.from('presenca').select('jogador').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id);aoVivoPresentes=(ps||[]).map(function(r){return r.jogador;});var{data:pts}=await sb.from('partidas').select('*').eq('pelada_id',peladaAtual.id).eq('grupo_id',grupoAtual.id).order('numero');var tp=pts||[];var at=tp.find(function(p){return p.status==='EmAndamento';})||null;if(at){var{data:gl}=await sb.from('gols').select('*').eq('partida_id',at.partida_id).eq('grupo_id',grupoAtual.id).order('timestamp');renderPartidaAtiva(at,gl||[],tp);setupRealtime(at.partida_id);}else{var pn=tp.length===0?1:tp[tp.length-1].numero+1;renderSetupPartida(tp,pn);if(realtimeChannel){sb.removeChannel(realtimeChannel);realtimeChannel=null;}}}
function setupRealtime(pid){if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel('av-'+pid).on('postgres_changes',{event:'*',schema:'public',table:'gols',filter:'partida_id=eq.'+pid},function(){loadAoVivo();}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'partidas',filter:'partida_id=eq.'+pid},function(){loadAoVivo();}).subscribe();}
function renderSetupPartida(tp,pn){var el=$('aoVivoContent');teamPicks={};var rh='';if(tp.length>0){rh='<div class="card"><div class="card-title">📋 Partidas</div>';tp.forEach(function(p){if(p.status!=='Finalizada')return;var vl=p.vencedor==='A'?'🔵 A':(p.vencedor==='B'?'🟠 B':'🤝 Emp');rh+='<div class="flex-between" style="padding:8px 0;border-bottom:1px solid rgba(36,48,73,0.3);font-size:13px;"><span>P'+p.numero+'</span><span style="font-weight:600;">'+p.placar_a+' x '+p.placar_b+'</span><span class="text-muted">'+vl+'</span></div>';});rh+='</div>';}var po=sa(aoVivoPresentes),ph='';po.forEach(function(n){ph+='<div class="pool-chip" data-player="'+n+'" onclick="pickPlayer(this)">'+dn(n)+'</div>';});el.innerHTML=rh+'<div class="card"><div class="card-title">⚽ Partida '+pn+'</div><div class="team-pick-label">1º=🔵A, 2º=🟠B, 3º=remove</div><div class="player-pool" id="playerPool">'+ph+'</div><div class="team-counters mt8">🔵 A: <span id="countA">0</span>/5 🟠 B: <span id="countB">0</span>/5</div></div><button class="btn btn-primary" onclick="iniciarPartida('+pn+')">Iniciar '+pn+'</button><button class="btn btn-danger mt12" onclick="confirmarEncerrarPelada()" style="margin-top:12px;">🏁 Encerrar</button>';}
function pickPlayer(c){var n=c.getAttribute('data-player'),cu=teamPicks[n]||null,cA=0,cB=0;for(var k in teamPicks){if(teamPicks[k]==='A')cA++;if(teamPicks[k]==='B')cB++;}if(cu===null){if(cA<5){teamPicks[n]='A';c.className='pool-chip team-a';}else if(cB<5){teamPicks[n]='B';c.className='pool-chip team-b';}}else if(cu==='A'){teamPicks[n]='B';c.className='pool-chip team-b';cB++;if(cB>5){teamPicks[n]=null;c.className='pool-chip';}}else{teamPicks[n]=null;c.className='pool-chip';}cA=0;cB=0;for(var k in teamPicks){if(teamPicks[k]==='A')cA++;if(teamPicks[k]==='B')cB++;}$('countA').textContent=cA;$('countB').textContent=cB;}
async function iniciarPartida(num){var tA=[],tB=[];for(var k in teamPicks){if(teamPicks[k]==='A')tA.push(k);if(teamPicks[k]==='B')tB.push(k);}if(tA.length!==5||tB.length!==5){showToast('5 por time!',true);return;}var pid=grupoAtual.id+'_'+peladaAtual.id+'_M'+String(num).padStart(2,'0');var{error:e}=await sb.from('partidas').insert({partida_id:pid,pelada_id:peladaAtual.id,numero:num,time_a:tA,time_b:tB,placar_a:0,placar_b:0,vencedor:'',status:'EmAndamento',grupo_id:grupoAtual.id});if(e){showToast(e.message,true);return;}showToast('Iniciada!');logAsync(currentUser,'INICIAR_PARTIDA',pid);loadAoVivo();}
function renderPartidaAtiva(part,gols,tp){var el=$('aoVivoContent');function bTR(pl,tl){var po=sa(pl),h='';po.forEach(function(n){h+='<div class="team-player-row"><span class="team-player-name">'+dn(n)+'</span><button class="goal-btn goal-btn-normal" onclick="mGol(\''+part.partida_id+'\',\''+n+'\',\''+tl+'\',false)">⚽</button><button class="goal-btn goal-btn-contra" onclick="mGol(\''+part.partida_id+'\',\''+n+'\',\''+tl+'\',true)">🔄</button></div>';});return h;}var gl='';if(gols.length>0){gl='<div class="card"><div class="card-title">⚽ Gols</div><div class="gol-log">';gols.forEach(function(g){var tc=g.time==='A'?'var(--blue)':'var(--orange)',tn=g.time==='A'?'A':'B';var lb=g.gol_contra?'🔄 GC '+dn(g.jogador)+' ('+tn+')':'⚽ '+dn(g.jogador)+' ('+tn+')';gl+='<div class="gol-item"><span style="color:'+tc+'">'+lb+'</span><button class="gol-remove" onclick="rGol(\''+g.gol_id+'\',\''+part.partida_id+'\')">✕</button></div>';});gl+='</div></div>';}el.innerHTML='<div class="scoreboard"><div class="scoreboard-match">Partida '+part.numero+'</div><div class="scoreboard-score"><span class="score-a">'+part.placar_a+'</span><span class="score-x">×</span><span class="score-b">'+part.placar_b+'</span></div><div class="scoreboard-labels"><span>🔵 A</span><span>🟠 B</span></div></div><div class="team-section"><div class="team-header team-header-a">🔵 Time A</div><div class="team-players">'+bTR(part.time_a,'A')+'</div></div><div class="team-section"><div class="team-header team-header-b">🟠 Time B</div><div class="team-players">'+bTR(part.time_b,'B')+'</div></div>'+gl+'<button class="btn btn-primary mt16" onclick="fPart(\''+part.partida_id+'\')">✅ Finalizar '+part.numero+'</button>';}
async function mGol(pid,j,t,gc){var{data:gid}=await sb.rpc('next_gol_id_grupo',{p_grupo_id:grupoAtual.id});await sb.from('gols').insert({gol_id:gid,partida_id:pid,pelada_id:peladaAtual.id,jogador:j,time:t,gol_contra:gc,grupo_id:grupoAtual.id});await sb.rpc('recalcular_placar',{p_partida_id:pid});showToast(gc?'Gol contra!':'Gol de '+dn(j)+'!');logAsync(currentUser,'GOL',j+' T'+t+(gc?' GC':''));loadAoVivo();}
async function rGol(gid,pid){if(!confirm('Remover?'))return;await sb.from('gols').delete().eq('gol_id',gid).eq('grupo_id',grupoAtual.id);await sb.rpc('recalcular_placar',{p_partida_id:pid});showToast('Removido.');loadAoVivo();}
async function fPart(pid){if(!confirm('Finalizar?'))return;var{data:p}=await sb.from('partidas').select('placar_a,placar_b').eq('partida_id',pid).eq('grupo_id',grupoAtual.id).single();var v=p.placar_a>p.placar_b?'A':(p.placar_b>p.placar_a?'B':'Empate');await sb.from('partidas').update({vencedor:v,status:'Finalizada'}).eq('partida_id',pid).eq('grupo_id',grupoAtual.id);showToast(v==='Empate'?'Empate!':(v==='A'?'🔵 A':'🟠 B')+' venceu!');logAsync(currentUser,'FIN_PART',pid);loadAoVivo();}
async function confirmarEncerrarPelada(){if(!confirm('Encerrar pelada?'))return;await sb.from('peladas').update({status:'Realizada'}).eq('id',peladaAtual.id).eq('grupo_id',grupoAtual.id);showToast('Encerrada!');logAsync(currentUser,'ENC_PELADA',peladaAtual.id);loadHome();navigateTo('Home');}
